global_costmap:
  # update_frequency: 2.5
  # publish_frequency: 2.5
  update_frequency: 1.5
  publish_frequency: 1.5
  transform_tolerance: 0.5
  width: 30
  height: 30
  origin_x: -15
  origin_y: -15
  static_map: false
  rolling_window: false
  inflation_radius: 1.5
  resolution: 0.1
  track_unknown_space: true
