global_costmap:
  # update_frequency: 2.5
  # publish_frequency: 2.5
  update_frequency: 1.5
  publish_frequency: 1.5
  transform_tolerance: 0.5
  width: 60
  height: 60
  origin_x: -30
  origin_y: -30
  static_map: false
  rolling_window: false
  inflation_radius: 2.0
  # inflation_radius: 0.14
  resolution: 0.1
  track_unknown_space: true
