local_costmap:
  # update_frequency: 5
  # publish_frequency: 5
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  origin_x: -2.5
  origin_y: -2.5
  resolution: 0.1
  # inflation_radius: 0.5
  inflation_radius: 0.12
